# Form implementation generated from reading ui file '.\window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 194)
        self.InputVoiceFile = QtWidgets.QLineEdit(Dialog)
        self.InputVoiceFile.setGeometry(QtCore.QRect(28, 39, 411, 21))
        self.InputVoiceFile.setObjectName("InputVoiceFile")
        self.NoiseSampleFile = QtWidgets.QLineEdit(Dialog)
        self.NoiseSampleFile.setGeometry(QtCore.QRect(27, 69, 411, 21))
        self.NoiseSampleFile.setObjectName("NoiseSampleFile")
        self.OutputCleanVoice = QtWidgets.QLineEdit(Dialog)
        self.OutputCleanVoice.setGeometry(QtCore.QRect(28, 99, 411, 21))
        self.OutputCleanVoice.setObjectName("OutputCleanVoice")
        self.RemoveNoise = QtWidgets.QPushButton(Dialog)
        self.RemoveNoise.setGeometry(QtCore.QRect(25, 132, 111, 41))
        self.RemoveNoise.setObjectName("RemoveNoise")
        self.BrowseInput = QtWidgets.QPushButton(Dialog)
        self.BrowseInput.setGeometry(QtCore.QRect(450, 40, 81, 21))
        self.BrowseInput.setObjectName("BrowseInput")
        self.BrowseNoise = QtWidgets.QPushButton(Dialog)
        self.BrowseNoise.setGeometry(QtCore.QRect(450, 70, 81, 21))
        self.BrowseNoise.setObjectName("BrowseNoise")
        self.BrowseOutput = QtWidgets.QPushButton(Dialog)
        self.BrowseOutput.setGeometry(QtCore.QRect(450, 102, 81, 21))
        self.BrowseOutput.setObjectName("BrowseOutput")
        self.GraphsOut = QtWidgets.QCheckBox(Dialog)
        self.GraphsOut.setGeometry(QtCore.QRect(170, 140, 251, 17))
        self.GraphsOut.setObjectName("GraphsOut")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.NoiseSampleFile, self.OutputCleanVoice)
        Dialog.setTabOrder(self.OutputCleanVoice, self.RemoveNoise)
        Dialog.setTabOrder(self.RemoveNoise, self.BrowseInput)
        Dialog.setTabOrder(self.BrowseInput, self.BrowseNoise)
        Dialog.setTabOrder(self.BrowseNoise, self.BrowseOutput)
        Dialog.setTabOrder(self.BrowseOutput, self.InputVoiceFile)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.InputVoiceFile.setToolTip(_translate("Dialog", "<html><head/><body><p>path to the file with voice sognal to process</p></body></html>"))
        self.InputVoiceFile.setText(_translate("Dialog", "Выберете файл для обработки (*.wav)"))
        self.RemoveNoise.setText(_translate("Dialog", "Remove Noise"))
        self.BrowseInput.setText(_translate("Dialog", "Выбрать"))
        self.BrowseNoise.setText(_translate("Dialog", "Выбрать"))
        self.BrowseOutput.setText(_translate("Dialog", "Выбрать"))
        self.GraphsOut.setText(_translate("Dialog", "Выводить визуализацию результатов"))
